# Generated by Django 4.2 on 2023-04-14 17:10

import defense.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_code', models.CharField(max_length=7)),
                ('subject', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='FinalPapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_code', models.CharField(default='None', max_length=7)),
                ('department', models.CharField(default='None', max_length=4)),
                ('base', models.CharField(default='None', max_length=4)),
                ('country', models.CharField(default='None', max_length=40)),
                ('mission', models.CharField(default='None', max_length=30)),
                ('paper', models.FileField(default=None, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tusername', models.CharField(default='None', max_length=40)),
                ('file_code', models.CharField(default='None', max_length=7)),
                ('file1', models.FileField(default=None, upload_to='')),
                ('file2', models.FileField(default=None, upload_to='')),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('enc_field', django.contrib.postgres.fields.ArrayField(base_field=models.BinaryField(default=None, max_length=500), default=list, size=None)),
                ('private_key', models.FileField(default=None, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('personal_id', models.CharField(blank=True, default=defense.models.personalID, max_length=20)),
                ('department', models.CharField(choices=[('None', 'None'), ('army', 'army')], default='None', max_length=5)),
                ('base', models.CharField(choices=[('None', 'None'), ('Al Dafra Base', 'Al Dafra Base'), ('Al Tanf Base', 'Al Tanf Base')], default='None', max_length=20)),
                ('country', models.CharField(choices=[('None', 'None'), ('United Arab Emirates', 'United Arab Emirates'), ('Syria', 'Syria')], default='None', max_length=40)),
                ('mission', models.CharField(choices=[('None', 'None'), ('Regional Security', 'Regional Security')], default='None', max_length=30)),
                ('role', models.CharField(choices=[('militarychief', 'militarychief'), ('militarypersonal', 'militarypersonal'), ('controlcenter', 'controlcenter')], default='militarychief', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
