# Generated by Django 4.2.1 on 2023-06-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0004_alter_request_file_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecode',
            name='file_code',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='finalpapers',
            name='file_code',
            field=models.CharField(default='None', max_length=70),
        ),
    ]
