# Generated by Django 4.2.1 on 2023-06-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0005_alter_filecode_file_code_alter_finalpapers_file_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalpapers',
            name='base',
            field=models.CharField(default='None', max_length=70),
        ),
        migrations.AlterField(
            model_name='finalpapers',
            name='department',
            field=models.CharField(default='None', max_length=70),
        ),
    ]
